name: Run all tests

on:
  push:

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0-beta.3
        with:
          gradle-version: 8.5

      - name: Run tests with Gradle
        run: gradle test
